[package]
name = "amele_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4", features = ["v4"] }
